# Generated by Django 2.2 on 2019-04-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(default='Misc', max_length=255),
            preserve_default=False,
        ),
    ]
